LOAD R


SET DIRECTORY WITH SIMULATION CODE
nohup Rscript "p5 runsim_female_RR07.R" > "p5 runsim_female_RR07.out"
nohup Rscript "p5 runsim_female_RR06.R" > "p5 runsim_female_RR06.out"
nohup Rscript "p5 runsim_female_RR065.R" > "p5 runsim_female_RR065.out"
nohup Rscript "p5 runsim_female_RR07_no1pres.R" > "p5 runsim_female_RR07_no1pres.out"
nohup Rscript "p5 runsim_female_RR06_no1pres.R" > "p5 runsim_female_RR06_no1pres.out"
nohup Rscript "p5 runsim_female_RR065_no1pres.R" > "p5 runsim_female_RR065_no1pres.out"
nohup Rscript "p5 runsim_male_RR07.R" > "p5 runsim_male_RR07.out"
nohup Rscript "p5 runsim_male_RR06.R" > "p5 runsim_male_RR06.out"
nohup Rscript "p5 runsim_male_RR065.R" > "p5 runsim_male_RR065.out"
nohup Rscript "p5 runsim_male_RR07_no1pres.R" > "p5 runsim_male_RR07_no1pres.out"
nohup Rscript "p5 runsim_male_RR06_no1pres.R" > "p5 runsim_male_RR06_no1pres.out"
nohup Rscript "p5 runsim_male_RR065_no1pres.R" > "p5 runsim_male_RR065_no1pres.out"

nohup Rscript "p6 runsim_female_RR07_discadj.R" > "p6 runsim_female_RR07_discadj.out"
nohup Rscript "p6 runsim_female_RR06_discadj.R" > "p6 runsim_female_RR06_discadj.out"
nohup Rscript "p6 runsim_female_RR065_discadj.R" > "p6 runsim_female_RR065_discadj.out"
nohup Rscript "p6 runsim_female_RR07_discadj_no1pres.R" > "p6 runsim_female_RR07_discadj_no1pres.out"
nohup Rscript "p6 runsim_female_RR06_discadj_no1pres.R" > "p6 runsim_female_RR06_discadj_no1pres.out"
nohup Rscript "p6 runsim_female_RR065_discadj_no1pres.R" > "p6 runsim_female_RR065_discadj_no1pres.out"
nohup Rscript "p6 runsim_male_RR07_discadj.R" > "p6 runsim_male_RR07_discadj.out"
nohup Rscript "p6 runsim_male_RR06_discadj.R" > "p6 runsim_male_RR06_discadj.out"
nohup Rscript "p6 runsim_male_RR065_discadj.R" > "p6 runsim_male_RR065_discadj.out"
nohup Rscript "p6 runsim_male_RR07_discadj_no1pres.R" > "p6 runsim_male_RR07_discadj_no1pres.out"
nohup Rscript "p6 runsim_male_RR06_discadj_no1pres.R" > "p6 runsim_male_RR06_discadj_no1pres.out"
nohup Rscript "p6 runsim_male_RR065_discadj_no1pres.R" > "p6 runsim_male_RR065_discadj_no1pres.out"

SET DIRECTORY WITH ANALYSIS CODE
nohup Rscript "p1 res_female_RR07.R" > "p1 res_female_RR07.out"
nohup Rscript "p1 res_female_RR06.R" > "p1 res_female_RR06.out"
nohup Rscript "p1 res_female_RR065.R" > "p1 res_female_RR065.out"
nohup Rscript "p1 res_female_RR07_no1pres.R" > "p1 res_female_RR07_no1pres.out"
nohup Rscript "p1 res_female_RR06_no1pres.R" > "p1 res_female_RR06_no1pres.out"
nohup Rscript "p1 res_female_RR065_no1pres.R" > "p1 res_female_RR065_no1pres.out"
nohup Rscript "p1 res_male_RR07.R" > "p1 res_male_RR07.out"
nohup Rscript "p1 res_male_RR06.R" > "p1 res_male_RR06.out"
nohup Rscript "p1 res_male_RR065.R" > "p1 res_male_RR065.out"
nohup Rscript "p1 res_male_RR07_no1pres.R" > "p1 res_male_RR07_no1pres.out"
nohup Rscript "p1 res_male_RR06_no1pres.R" > "p1 res_male_RR06_no1pres.out"
nohup Rscript "p1 res_male_RR065_no1pres.R" > "p1 res_male_RR065_no1pres.out"

nohup Rscript "p2 res_female_RR07_discadj.R" > "p2 res_female_RR07_discadj.out"
nohup Rscript "p2 res_female_RR06_discadj.R" > "p2 res_female_RR06_discadj.out"
nohup Rscript "p2 res_female_RR065_discadj.R" > "p2 res_female_RR065_discadj.out"
nohup Rscript "p2 res_female_RR07_discadj_no1pres.R" > "p2 res_female_RR07_discadj_no1pres.out"
nohup Rscript "p2 res_female_RR06_discadj_no1pres.R" > "p2 res_female_RR06_discadj_no1pres.out"
nohup Rscript "p2 res_female_RR065_discadj_no1pres.R" > "p2 res_female_RR065_discadj_no1pres.out"
nohup Rscript "p2 res_male_RR07_discadj.R" > "p2 res_male_RR07_discadj.out"
nohup Rscript "p2 res_male_RR06_discadj.R" > "p2 res_male_RR06_discadj.out"
nohup Rscript "p2 res_male_RR065_discadj.R" > "p2 res_male_RR065_discadj.out"
nohup Rscript "p2 res_male_RR07_discadj_no1pres.R" > "p2 res_male_RR07_discadj_no1pres.out"
nohup Rscript "p2 res_male_RR06_discadj_no1pres.R" > "p2 res_male_RR06_discadj_no1pres.out"
nohup Rscript "p2 res_male_RR065_discadj_no1pres.R" > "p2 res_male_RR065_discadj_no1pres.out"